// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb2dBbEOiY03iJMB8f3o_Urg7YEFLO7wM',
    appId: '1:783803972398:web:6be08b953369dd722c58bf',
    messagingSenderId: '783803972398',
    projectId: 'flutterfire-gallery-202119',
    authDomain: 'flutterfire-gallery-202119.firebaseapp.com',
    storageBucket: 'flutterfire-gallery-202119.appspot.com',
    measurementId: 'G-VRHKN20G1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA8hWpLDp_HX1xKlEYGesp0fU6ZNHXxBM',
    appId: '1:783803972398:android:7dda3e8dd5fa97972c58bf',
    messagingSenderId: '783803972398',
    projectId: 'flutterfire-gallery-202119',
    storageBucket: 'flutterfire-gallery-202119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-u4jP--PQkI3TKrcnSDGM93Wbbl35so',
    appId: '1:783803972398:ios:cd2e707d2c1c3ead2c58bf',
    messagingSenderId: '783803972398',
    projectId: 'flutterfire-gallery-202119',
    storageBucket: 'flutterfire-gallery-202119.appspot.com',
    iosClientId: '783803972398-nhce15skhcbkdofeprfc038407kkgefh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG-u4jP--PQkI3TKrcnSDGM93Wbbl35so',
    appId: '1:783803972398:ios:cd2e707d2c1c3ead2c58bf',
    messagingSenderId: '783803972398',
    projectId: 'flutterfire-gallery-202119',
    storageBucket: 'flutterfire-gallery-202119.appspot.com',
    iosClientId: '783803972398-nhce15skhcbkdofeprfc038407kkgefh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireGallery',
  );
}
